const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Arr.Acts.SplitString,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Browser.Acts.RequestFullScreen
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Mouse: 0},
	{Audio: 0},
	{Array: 0},
	{Sine: 0},
	{btn_play: 0},
	{giris: 0},
	{girisyazi: 0},
	{oyunEkran: 0},
	{sorular: 0},
	{agac: 0},
	{btn_home: 0},
	{btn_kaynakca: 0},
	{btn_sesac: 0},
	{btn_seskapat: 0},
	{btn_emgecen: 0},
	{btn_bilgi: 0},
	{Tween: 0},
	{tebrikleryazi: 0},
	{bant_kirmizi: 0},
	{bant_yesil: 0},
	{bant_seffaf: 0},
	{cvp_1: 0},
	{cvp_2: 0},
	{cvp_3: 0},
	{cvp_4: 0},
	{cvp_5: 0},
	{cvp_6: 0},
	{cvp_7: 0},
	{cvp_8: 0},
	{cvp_9: 0},
	{cvp_10: 0},
	{cvp_11: 0},
	{cvp_12: 0},
	{cvp_13: 0},
	{cvp_14: 0},
	{cvp_15: 0},
	{cvp_16: 0},
	{cvp_17: 0},
	{cvp_18: 0},
	{cvp_19: 0},
	{cvp_20: 0},
	{btn_akranbuyut: 0},
	{btn_ekrankucult: 0},
	{meblogobeyaz: 0},
	{kapak: 0},
	{btn_tekraroyna: 0},
	{Browser: 0},
	{btn_ok: 0},
	{infooo: 0},
	{sayilar: 0},
	{agac2: 0},
	{agac3: 0},
	{agac4: 0},
	{agac5: 0},
	{agac6: 0},
	{agac7: 0},
	{agac8: 0},
	{agac9: 0},
	{agac10: 0},
	{agac11: 0},
	{agac12: 0},
	{agac13: 0},
	{agac14: 0},
	{agac15: 0},
	{agac16: 0},
	{agac17: 0},
	{agac18: 0},
	{agac19: 0},
	{agac20: 0},
	{score: 0},
	{agactebrik: 0},
	{sure_halka: 0},
	{Timer: 0},
	{sure_Text: 0},
	{correct: 0},
	{wrong: 0},
	{dogrusayisi: 0},
	{yanlisSayisi: 0},
	{btns: 0},
	{cvplar: 0},
	{handolsun: 0},
	{soru_no: 0},
	{bekleme: 0},
	{infopage: 0},
	{dogru_sayisi: 0},
	{yanlis_sayisi: 0},
	{sure_deg: 0},
	{tiklama: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	btn_play: class extends self.ISpriteInstance {},
	giris: class extends self.ISpriteInstance {},
	girisyazi: class extends self.ISpriteInstance {},
	oyunEkran: class extends self.ISpriteInstance {},
	sorular: class extends self.ISpriteInstance {},
	agac: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	btn_kaynakca: class extends self.ISpriteInstance {},
	btn_sesac: class extends self.ISpriteInstance {},
	btn_seskapat: class extends self.ISpriteInstance {},
	btn_emgecen: class extends self.ISpriteInstance {},
	btn_bilgi: class extends self.ISpriteInstance {},
	tebrikleryazi: class extends self.ISpriteInstance {},
	bant_kirmizi: class extends self.ISpriteInstance {},
	bant_yesil: class extends self.ISpriteInstance {},
	bant_seffaf: class extends self.ISpriteInstance {},
	cvp_1: class extends self.ISpriteInstance {},
	cvp_2: class extends self.ISpriteInstance {},
	cvp_3: class extends self.ISpriteInstance {},
	cvp_4: class extends self.ISpriteInstance {},
	cvp_5: class extends self.ISpriteInstance {},
	cvp_6: class extends self.ISpriteInstance {},
	cvp_7: class extends self.ISpriteInstance {},
	cvp_8: class extends self.ISpriteInstance {},
	cvp_9: class extends self.ISpriteInstance {},
	cvp_10: class extends self.ISpriteInstance {},
	cvp_11: class extends self.ISpriteInstance {},
	cvp_12: class extends self.ISpriteInstance {},
	cvp_13: class extends self.ISpriteInstance {},
	cvp_14: class extends self.ISpriteInstance {},
	cvp_15: class extends self.ISpriteInstance {},
	cvp_16: class extends self.ISpriteInstance {},
	cvp_17: class extends self.ISpriteInstance {},
	cvp_18: class extends self.ISpriteInstance {},
	cvp_19: class extends self.ISpriteInstance {},
	cvp_20: class extends self.ISpriteInstance {},
	btn_akranbuyut: class extends self.ISpriteInstance {},
	btn_ekrankucult: class extends self.ISpriteInstance {},
	meblogobeyaz: class extends self.ISpriteInstance {},
	kapak: class extends self.ISpriteInstance {},
	btn_tekraroyna: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	btn_ok: class extends self.ISpriteInstance {},
	infooo: class extends self.ISpriteInstance {},
	sayilar: class extends self.ISpriteInstance {},
	agac2: class extends self.ISpriteInstance {},
	agac3: class extends self.ISpriteInstance {},
	agac4: class extends self.ISpriteInstance {},
	agac5: class extends self.ISpriteInstance {},
	agac6: class extends self.ISpriteInstance {},
	agac7: class extends self.ISpriteInstance {},
	agac8: class extends self.ISpriteInstance {},
	agac9: class extends self.ISpriteInstance {},
	agac10: class extends self.ISpriteInstance {},
	agac11: class extends self.ISpriteInstance {},
	agac12: class extends self.ISpriteInstance {},
	agac13: class extends self.ISpriteInstance {},
	agac14: class extends self.ISpriteInstance {},
	agac15: class extends self.ISpriteInstance {},
	agac16: class extends self.ISpriteInstance {},
	agac17: class extends self.ISpriteInstance {},
	agac18: class extends self.ISpriteInstance {},
	agac19: class extends self.ISpriteInstance {},
	agac20: class extends self.ISpriteInstance {},
	score: class extends self.ISpriteInstance {},
	agactebrik: class extends self.ISpriteInstance {},
	sure_halka: class extends self.ISpriteInstance {},
	sure_Text: class extends self.ITextInstance {},
	correct: class extends self.ISpriteInstance {},
	wrong: class extends self.ISpriteInstance {},
	dogrusayisi: class extends self.ISpriteInstance {},
	yanlisSayisi: class extends self.ISpriteInstance {},
	btns: class extends self.ISpriteInstance {},
	cvplar: class extends self.ISpriteInstance {},
	handolsun: class extends self.ISpriteInstance {}
}